### PR TITLE
Langs deck

### PR DESCRIPTION
**Pull request by starbelly**
This commit intends to add a languages deck on the main page. Things to figure out  : 

1. What do we do about languages that don't have logos? 

2. Where do we want to place the deck? 

3. Do we shuffle on every draw or every N second?

### CODE REVIEW

**Comment by starbelly** [comment]
Logo sizes and such still need to be done, and whether to use borders etc, but that should be done last.

**Comment by pablocostass** [comment]
Can you force push to trigger the deployment? Damn you Github! :(

**Comment by starbelly** [comment]
Hmm, since the images are links that shuffle every N should either go away or be changed to like every 60 seconds. If you go to click a link and it shuffles, bad ux :p

**Comment by paulo-ferraz-oliveira** [comment]
1. What do we do about languages that don't have logos?

We ask the creators if they wanna sponsor SpawnFest :) to get the "right" to have their lang. name mentioned (jk)

2. Where do we want to place the deck?

No strong opinion, but I'm Okay if you wanna put it here: https://spawnfest.org/#registration

3. Do we shuffle on every draw or every N second?

I wouldn't bother, not this year. Probably create a task, though, in any case; if a pull request surfaces we'll close the task.

**Comment by starbelly** [comment]
>     1. What do we do about languages that don't have logos?
> 
> 
> We ask the creators if they wanna sponsor SpawnFest :) to get the "right" to have their lang. name mentioned (jk)

  :) Nah, what I meant, is do we include languages that don't have logos? I'm going to opt to say no for right now, not aiming for perfection. 

> 
>     1. Where do we want to place the deck?
> 
> 
> No strong opinion, but I'm Okay if you wanna put it here: https://spawnfest.org/#registration
> 
 
 That makes sense to me. 

>     1. Do we shuffle on every draw or every N second?
> 
> 
> I wouldn't bother, not this year. Probably create a task, though, in any case; if a pull request surfaces we'll close the task. (note: I'd only shuffle on render, not animated)

 Already removed the "shuffle every N" part per bad UX that can ensue.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira I opted to leave in about section with a call out above it. Trying to wedge into registration didn't feel right. Still need to remove logos from registration.

**Review by pablocostass — APPROVED** [review]

**Pull request merged**
