### PR TITLE
Add a Gemfile and Gemfile.lock

### PR DESCRIPTION
**Pull request by starbelly**

### CODE REVIEW

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira so we need to update the README.md. I would do this as part of this PR, but we need to agree on a thing.... ruby 3? 

IMO, I'd like to move to hugo, but not this year.

**Review by paulo-ferraz-oliveira — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira so we need to update the README.md. I would do this as part of this PR, but we need to agree on a thing.... ruby 3?
> 
> IMO, I'd like to move to hugo, but not this year.

Ruby 3's not working for me, locally. What's the requirement?

Does `jekyll` not run for ruby 2 and 3?

Also, how easy is it to deploy Hugo locally (never used it - don't understand advantages over Jekyll).

**Comment by paulo-ferraz-oliveira** [comment]
I moved the base to `2021`. Lets keep it like that until we want to merge `2021` to `master` (some time before the event, but not just yet).

**Comment by starbelly** [comment]
To be clear, this doesn't change us to ruby3, I was just saying well, since ruby 3.x has been out, we might as well switch and recommend using the latest. We should at the very least recommend 2.7 though. 

> I moved the base to 2021. Lets keep it like that until we want to merge 2021 to master (some time before the event, but not just yet).

Not sure why? We'll be updating the site a lot in months leading up to the event 🤔 I'm not sure why this never had a Gemfile but it always should have IMO.

**Comment by starbelly** [comment]
We can circle back to handling the README, etc.

**Comment by paulo-ferraz-oliveira** [comment]
> To be clear, this doesn't change us to ruby3, I was just saying well, since ruby 3.x has been out, we might as well switch and recommend using the latest. We should at the very least recommend 2.7 though.
> 
> > I moved the base to 2021. Lets keep it like that until we want to merge 2021 to master (some time before the event, but not just yet).
> 
> Not sure why? We'll be updating the site a lot in months leading up to the event 🤔 I'm not sure why this never had a Gemfile but it always should have IMO.

Well, once we have the first edition "2021" ready we can merge to "main". I just don't want to do it in small steps. Even if nobody's paying attention to the site at this moment, it'd remain "broken".

**Pull request merged**
