### PR TITLE
Reverse previous hunk for UI improvements

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Let's see if this is it.

**Note**: don't do multiple CSS + HTML stuff at once lest we have to revert some.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Ah, much better.

**Comment by paulo-ferraz-oliveira** [comment]
@pablocostass, can you tell if this is Okay in your browser, phone, whatever (?) It's a very small change, but I'd like to merge.

**Review by starbelly — APPROVED** [review]
Indeed looks fine on my iphone! ❤️

**Comment by paulo-ferraz-oliveira** [comment]
Let's do this.

**Comment by paulo-ferraz-oliveira** [comment]
DOIT

**Pull request merged**
