### PR TITLE
Add judges for 2023

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
The first commit is just a little something something to make the social media stuff more generic.

After that I'll do a commit per judge, as the info arrives, and I'll tag the judges here for validation.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@adolfont, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@jj1bdx, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

**Comment by adolfont** [comment]
> @adolfont, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

It is OK. Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
@kikofernandez, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
@evadne, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

**Comment by elbrujohalcon** [comment]
> @elbrujohalcon, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

Perfect 👍

**Review by elbrujohalcon — APPROVED** [review]

**Comment by evadne** [comment]
> @evadne, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

👍

**Comment by jj1bdx** [comment]
> @jj1bdx, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

Looked OK! Thanks!

**Comment by kikofernandez** [comment]
> @kikofernandez, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

Looks great, thanks!

**Comment by paulo-ferraz-oliveira** [comment]
@rvirding, you're added here 😄. Wanna review the result: https://deploy-preview-182--spawnfestgithubio.netlify.app/#judges? Thanks.

**Pull request merged**
