### PR TITLE
Archive 2020

### LINKED ISSUE #80: Sponsorship contact email update
At `sponsors.html` we need to revisit the "Be a Sponsor!" associated e-mail.

Should we set one up somewhere?

### LINKED ISSUE #83: Update organizer in _config.yml
Currently `fiqus`.

### PR DESCRIPTION
**Pull request by pablocostass**
This commit archives all the info (pictures, participants) we had from 2020 and also hides the prizes list, judges, etc.

The date of the event has been hidden by simply removing the date from the logo (will fight to add it properly later).

Also, in my sleepy state, I might have added some duplicate pictures in `img/legacy`, but I shall amend that in another PR.

Closes #83. Closes #80.

### CODE REVIEW

**Review by starbelly — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Cool stuff. I don't mind merging as is, but I'd hide project ideas until we decide we want them there, or we refresh them.

**Review by paulo-ferraz-oliveira — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Issue https://github.com/spawnfest/spawnfest.github.io/issues/92 created for the project ideas.

**Comment by pablocostass** [comment]
For now I have hidden them, I will ponder about how to improve the section today :)

**Comment by paulo-ferraz-oliveira** [comment]
I'm Okay with continuous merging; smaller PRs, so some don't affect the others (merge-wise).

**Pull request merged**
